properties
arrowPlacementProp: propValue 
"'The placement of the arrow. The default is  anchor , which will align the arrow as close to the center of the anchor as possible, considering available space and  arrow-padding . A value of  start ,  end , or  center  will align the arrow to the start, end, or center of the popover instead.
type: 'start' | 'end' | 'center' | 'anchor'
default: 'anchor''"

self attributeAt: #'arrowPlacement' put: propValue