attributes
autoSizeBoundary: attrValue 
"'The auto-size boundary describes clipping element(s) that overflow will be checked relative to when resizing. By default, the boundary includes overflow ancestors that will cause the element to be clipped. If needed, you can change the boundary by passing a reference to one or more elements to this property.
type: Element | Element[]'"

self attributeAt: #'autoSizeBoundary' put: attrValue