attributes
shiftBoundary: attrValue 
"'The shift boundary describes clipping element(s) that overflow will be checked relative to when shifting. By default, the boundary includes overflow ancestors that will cause the element to be clipped. If needed, you can change the boundary by passing a reference to one or more elements to this property.
type: Element | Element[]'"

self attributeAt: #'shiftBoundary' put: attrValue