attributes
placement: attrValue 
"'The preferred placement of the color picker's popup. Note that the actual placement will vary as configured to keep the panel inside of the viewport.
type: | 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'right' | 'right-start' | 'right-end' | 'left' | 'left-start' | 'left-end'
default: 'bottom-start''"

self attributeAt: #'placement' put: attrValue