attributes
family: attrValue 
"'The family of icons to choose from. For Font Awesome Free, valid options include  classic  and  brands . For Font Awesome Pro subscribers, valid options include,  classic ,  sharp ,  duotone ,  sharp-duotone , and  brands . A valid kit code must be present to show pro icons via CDN. You can set  <html data-fa-kit-code='...'>  to provide one.
type: string'"

self attributeAt: #'family' put: attrValue