attributes
playbackRate: attrValue 
"'Sets the animation's playback rate. The default is  1 , which plays the animation at a normal speed. Setting this to  2 , for example, will double the animation's speed. A negative value can be used to reverse the animation. This value can be changed without causing the animation to restart.
type: number
default: 1'"

self attributeAt: #'playback-rate' put: attrValue